### ISSUE TITLE
A question about the promoter-capture HiC data 

### ISSUE THREAD

**Issue by yunqiyang0215** [caleblareau/singlecell_bloodtraits#1]
Hi, 

I am a PhD student at UChicago, and we intend to use your promoter-capture HiC data for our own research. We have a set of significant eQTLs from the whole blood, and would like to know if these SNPs are captured by some promoters from HiC and also the target genes of those promoters. 

I am looking at your data: singlecell_bloodtraits/data/pchic/pchic.rds, and it seems promising for our use. But I have a question here. I am wondering for your HiC data, apart from filtering based on Chicago score >5, did you limit to the SNPs that are only related to the 16 traits?

Thanks for your help.
Best,
Yunqi

**Comment by caleblareau** [comment]
Hi, 

The primary source for the data (https://pubmed.ncbi.nlm.nih.gov/27863249/ <https://pubmed.ncbi.nlm.nih.gov/27863249/>) may be the best source, but as I recall, we did not filter any data in a SNP-specific manner that is in the RDS file that you mentioned.

**Comment by yunqiyang0215** [comment]
Thanks for your help, Caleb. This information is useful.
